CREATE DATABASE jvtcGroupOfRobot CHARSET utf8
USE jvtcGroupOfRobot;

CREATE TABLE user(
	id INT PRIMARY KEY AUTO_INCREMENT, 
	username VARCHAR(15) UNIQUE NOT NULL, 
	password VARCHAR(15) NOT NULL, 
	email VARCHAR(30) NOT NULL
);

CREATE TABLE pushTesk(
	id INT PRIMARY KEY AUTO_INCREMENT,
	jiaoWuUsername VARCHAR(15) NOT NULL, 
	jiaoWuPassword VARCHAR(15) NOT NULL, 
	groupId VARCHAR(15) NOT NULL UNIQUE, 
	accountId VARCHAR(15) NOT NULL, 
	push_hour_min VARCHAR(5) NOT NULL, 
	className VARCHAR(15) NOT NULL, 
	isPush BOOLEAN NOT NULL, 
	isNowCourse BOOLEAN NOT NULL
);

CREATE TABLE userToPushTesk(
	id INT PRIMARY KEY AUTO_INCREMENT, 
	username VARCHAR(15) NOT NULL, FOREIGN KEY(username) REFERENCES USER(username), 
	pushTeskId INT NOT NULL, FOREIGN KEY(pushTeskId) REFERENCES pushTesk(id) ON DELETE CASCADE
);
